const SUPABASE_URL="https://dspemuisfagoxwkpluyh.supabase.co";
const SUPABASE_KEY="sb_publishable_Lnq7CwIrAV9AJQjOVtFijw_CbD96Jar";
const db=supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const $=id=>document.getElementById(id);
let mode="signup", pendingEmail="", filter="All", verifiedUser=null;
const opportunities=[
 {id:1,type:"Learn",title:"Cybersecurity learning path",meta:"Self-paced · Skills · Global",trust:"✓ Verified source",desc:"Build practical security foundations and collect proof as you progress."},
 {id:2,type:"Compete",title:"Open technology challenge",meta:"Project challenge · Free entry · Global",trust:"✓ Verified source",desc:"Create a practical project and turn the result into portfolio evidence."},
 {id:3,type:"Learn",title:"AI & automation sprint",meta:"Beginner friendly · Online",trust:"✓ Verified source",desc:"A focused sprint for learning useful AI workflows through practice."},
 {id:4,type:"Work",title:"Career opportunities · 18+",meta:"Eligibility required · Adult roles",trust:"🔒 Age-gated",desc:"Adult work opportunities are kept behind an 18+ eligibility gate."},
 {id:5,type:"Compete",title:"Security skills sprint",meta:"Short challenge · Portfolio proof",trust:"✓ Verified source",desc:"Practice defensive security thinking and record your achievement."},
 {id:6,type:"Learn",title:"Scholarship research hub",meta:"Funding · Global · Free",trust:"✓ Verified source",desc:"Discover funding research methods and organize application evidence."}
];
const saved=()=>JSON.parse(localStorage.getItem("or_saved")||"[]");
const saveIds=()=>{localStorage.setItem("or_saved",JSON.stringify(saved()));updateSavedCount()};
function updateSavedCount(){const n=saved().length;document.querySelectorAll("[data-saved-count]").forEach(x=>x.textContent=n)}
function toast(msg,ok=true){let t=$("toast");if(!t){t=document.createElement("div");t.id="toast";t.style.cssText="position:fixed;right:18px;bottom:18px;z-index:100;background:#10233a;border:1px solid #356080;color:#fff;padding:13px 16px;border-radius:12px;box-shadow:0 15px 40px rgba(0,0,0,.35);max-width:340px";document.body.appendChild(t)}t.textContent=msg;t.style.borderColor=ok?"#356080":"#8a4450";clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.remove(),3200)}
function renderOpps(){const q=$("search").value.toLowerCase();const list=opportunities.filter(o=>(filter==="All"||o.type===filter)&&(`${o.title} ${o.meta} ${o.desc}`.toLowerCase().includes(q)));$("oppList").innerHTML=list.map(o=>{const isSaved=saved().includes(o.id);return `<article class="card opp"><span class="trust">${o.trust}</span><span class="tag">${o.type}</span><h3>${o.title}</h3><div class="meta">${o.meta}</div><p style="margin-top:10px">${o.desc}</p><div style="display:flex;gap:8px;margin-top:15px"><button class="btn primary" onclick="openOpportunity(${o.id})">View details →</button><button class="btn" onclick="toggleSave(${o.id)}">${isSaved?"★ Saved":"☆ Save"}</button></div></article>`}).join("")||`<article class="card"><h3>No matching signals</h3><p>Try another search. The algorithm has not yet conquered the entire universe.</p></article>`;$("radarCount").textContent=list.length;updateSavedCount()}
function openOpportunity(id){const o=opportunities.find(x=>x.id===id);if(!o)return;if(o.type==="Work"){toast("Work listings are 18+ and cannot be opened from this account.",false);return}openAuth("login");toast(`Sign in to open: ${o.title}`)}
function toggleSave(id){const arr=saved();const i=arr.indexOf(id);if(i>=0){arr.splice(i,1);toast("Removed from your saved radar.")}else{arr.push(id);toast("Saved to your radar.")}localStorage.setItem("or_saved",JSON.stringify(arr));renderOpps()}
function lockScreen(){document.body.dataset.locked="true";openAuth("signup");}
function openAuth(nextMode="signup"){mode=nextMode;$("authModal").classList.remove("hidden");$("emailStep").classList.remove("hidden");$("otpStep").classList.add("hidden");$("authStatus").textContent="";$("otpStatus").textContent="";$("authEmail").value=pendingEmail;$("authTitle").textContent=mode==="signup"?"Create your account":"Welcome back";$("authSubtitle").textContent="Use your Gmail address. We will email you a secure verification link. Access opens only after your email is verified.";$("nameField").classList.toggle("hidden",mode!=="signup");$("switchLogin").classList.toggle("hidden",mode!=="signup");$("authEyebrow").textContent="STEP 1 OF 2";$("step1").classList.add("on");$("step2").classList.remove("on");setTimeout(()=>$("authEmail").focus(),50)}
function closeAuth(){if(!verifiedUser&&document.body.dataset.locked==="true"){toast("Verify your Gmail first. Your account is still locked.",false);return}$("authModal").classList.add("hidden")}
async function sendCode(){const email=$("authEmail").value.trim().toLowerCase();const status=$("authStatus");if(!/^\S+@gmail\.com$/i.test(email)){status.className="status error";status.textContent="Please use a valid Gmail address.";return}if(mode==="signup"&&!$("authName").value.trim()){status.className="status error";status.textContent="Enter your name first.";return}pendingEmail=email;status.className="status";status.textContent="Sending your secure verification email…";$("sendOtp").disabled=true;const {error}=await db.auth.signInWithOtp({email,options:{shouldCreateUser:mode==="signup",data:mode==="signup"?{full_name:$("authName").value.trim()}:undefined,emailRedirectTo:location.href}});$("sendOtp").disabled=false;if(error){status.className="status error";status.textContent=error.message;return}$("emailStep").classList.add("hidden");$("otpStep").classList.remove("hidden");$("authEyebrow").textContent="STEP 2 OF 2";$("step1").classList.remove("on");$("step2").classList.add("on");$("otpStatus").className="status ok";$("otpStatus").textContent="Check your Gmail and tap the verification link. This page will unlock automatically."}
async function finishAccess(user){if(!user)return;const confirmed=!!user.email_confirmed_at;if(!confirmed){lockScreen();return}verifiedUser=user;document.body.dataset.locked="false";const name=user.user_metadata?.full_name||user.email?.split("@")[0]||"Member";const {error}=await db.from("profiles").upsert({id:user.id,display_name:name},{onConflict:"id"});if(error)console.warn("Profile sync:",error.message);closeAuth();$("accountArea").classList.remove("hidden");$("loginBtn").classList.add("hidden");$("signupBtn").classList.add("hidden");$("accountEmail").textContent=user.email;$("dashboard").classList.add("show");$("welcome").textContent=`Welcome, ${name}. Your Gmail is verified and your account is unlocked.`;$("savedStat").textContent=saved().length;window.scrollTo({top:document.getElementById("dashboard").offsetTop-80,behavior:"smooth"});toast("Email verified. Opportunity Radar unlocked.")}
async function restoreSession(){const {data}=await db.auth.getSession();if(data.session&&data.session.user?.email_confirmed_at){await finishAccess(data.session.user)}else{verifiedUser=null;$("accountArea").classList.add("hidden");$("loginBtn").classList.remove("hidden");$("signupBtn").classList.remove("hidden");setTimeout(lockScreen,150)}}
async function logout(){await db.auth.signOut();verifiedUser=null;document.body.dataset.locked="true";$("dashboard").classList.remove("show");$("accountArea").classList.add("hidden");$("loginBtn").classList.remove("hidden");$("signupBtn").classList.remove("hidden");toast("Signed out. The radar is locked again.");setTimeout(()=>openAuth("signup"),150)}
document.querySelectorAll("[data-scroll]").forEach(b=>b.addEventListener("click",()=>document.getElementById(b.dataset.scroll)?.scrollIntoView({behavior:"smooth"})));
document.querySelectorAll("[data-filter]").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll("[data-filter]").forEach(x=>x.classList.remove("active"));b.classList.add("active");filter=b.dataset.filter;renderOpps()}));
$("search").addEventListener("input",renderOpps);$("signupBtn").onclick=()=>openAuth("signup");$("heroSignup").onclick=()=>openAuth("signup");$("loginBtn").onclick=()=>openAuth("login");$("closeAuth").onclick=closeAuth;$("sendOtp").onclick=sendCode;$("verifyOtp").onclick=()=>toast("Verification happens through the secure Gmail link in this version.");$("resendOtp").onclick=sendCode;$("changeEmail").onclick=()=>openAuth(mode);$("switchLogin").onclick=()=>openAuth("login");$("logoutBtn").onclick=logout;$("authModal").addEventListener("click",e=>{if(e.target.id==="authModal")closeAuth()});
db.auth.onAuthStateChange((_event,session)=>{if(session?.user)finishAccess(session.user)});
renderOpps();updateSavedCount();restoreSession();
