(() => {
const U='https://dspemuisfagoxwkpluyh.supabase.co',K='sb_publishable_Lnq7CwIrAV9AJQjOVtFijw_CbD96Jar',db= supabase.createClient(U,K);
const esc=v=>String(v??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[m]));
const currencies=['AUD','BRL','CAD','CHF','CNY','EUR','GBP','GHS','INR','JPY','KES','NGN','NOK','NZD','PKR','RUB','SAR','SEK','SGD','USD','XAF','XOF','ZAR'];
const countryNames=['Argentina','Australia','Austria','Bangladesh','Belgium','Brazil','Canada','China','Colombia','Egypt','France','Germany','Ghana','India','Indonesia','Ireland','Italy','Japan','Kenya','Mexico','Netherlands','New Zealand','Nigeria','Norway','Pakistan','Philippines','Portugal','Rwanda','Saudi Arabia','Singapore','South Africa','South Korea','Spain','Sweden','Switzerland','Tanzania','Thailand','Türkiye','United Arab Emirates','United Kingdom','United States','Vietnam','Zambia'];
const detect=()=>((navigator.language||'').match(/[-_]([A-Z]{2})$/i)||[])[1]?.toUpperCase()||'';
const s={country:localStorage.getItem('or_country')||detect(),currency:localStorage.getItem('or_currency')||'',language:localStorage.getItem('or_language')||((navigator.language||'en').split('-')[0])};
const currencyFor={NG:'NGN',IN:'INR',CN:'CNY',DE:'EUR',GB:'GBP',US:'USD',CA:'CAD',AU:'AUD',JP:'JPY',GH:'GHS',KE:'KES',ZA:'ZAR',CH:'CHF',NO:'NOK',SE:'SEK',NZ:'NZD',BR:'BRL',MX:'MXN'};
s.currency=s.currency||currencyFor[s.country]||'USD';
function inject(){const top=document.querySelector('.top-actions');if(!top||document.getElementById('orLocale'))return;const b=document.createElement('div');b.id='orLocale';b.className='locale-controls';b.innerHTML='<input id="orCountry" list="orCountries" placeholder="Country" aria-label="Country"><datalist id="orCountries">'+countryNames.map(x=>`<option value="${esc(x)}">`).join('')+'</datalist><select id="orCurrency" aria-label="Display currency">'+currencies.map(x=>`<option>${x}</option>`).join('')+'</select><select id="orLanguage" aria-label="Language"><option value="en">English</option><option value="fr">Français</option><option value="es">Español</option><option value="pt">Português</option><option value="de">Deutsch</option><option value="hi">हिन्दी</option><option value="zh">中文</option><option value="ar">العربية</option><option value="ja">日本語</option></select>';top.insertBefore(b,top.firstChild);document.getElementById('orCountry').value=s.country;document.getElementById('orCurrency').value=s.currency;document.getElementById('orLanguage').value=s.language;document.getElementById('orCountry').onchange=persist;document.getElementById('orCurrency').onchange=persist;document.getElementById('orLanguage').onchange=persist;}
async function persist(){s.country=document.getElementById('orCountry').value.trim();s.currency=document.getElementById('orCurrency').value;s.language=document.getElementById('orLanguage').value;localStorage.setItem('or_country',s.country);localStorage.setItem('or_currency',s.currency);localStorage.setItem('or_language',s.language);document.documentElement.lang=s.language;const u=(await db.auth.getUser()).data.user;if(u)await db.from('profiles').upsert({id:u.id,country:s.country||null,preferred_currency:s.currency,preferred_language:s.language,locale:`${s.language}-${s.country||'US'}`,timezone:Intl.DateTimeFormat().resolvedOptions().timeZone||'UTC',updated_at:new Date().toISOString()});}
function globalCopy(){const l=document.querySelector('.hero .lead');if(l)l.textContent='Learn with people anywhere. Build proof of skill. Discover opportunities relevant to you while keeping the world open.';const n1=document.querySelector('.n1'),n2=document.querySelector('.n2'),n3=document.querySelector('.n3');if(n1)n1.innerHTML='🌐 <b>Your country</b><small>Localized context</small>';if(n2)n2.innerHTML='◈ <b>Optional region</b><small>Only when relevant</small>';if(n3)n3.innerHTML='🌍 <b>World</b><small>Global by default</small>';const p=document.querySelector('#world-series .section-head p');if(p)p.textContent='Every competition defines its own published stage model. Some may use country → region → world. Others may be global qualifiers, university → national → global, or another transparent structure.';const rail=document.querySelector('#world-series .stage-rail');if(rail)rail.innerHTML='<div class="stage active"><small>01</small><b>OPEN</b><span>Global or local qualifier</span></div><i>→</i><div class="stage"><small>02</small><b>EVENT-DEFINED</b><span>Country, university, region or open</span></div><i>→</i><div class="stage"><small>03</small><b>FINAL</b><span>Published event rules</span></div>';}
async function refreshOpp(){const h=document.querySelector('#opportunityPreview');if(!h)return;const {data}=await db.from('opportunities').select('*').order('score',{ascending:false}).limit(3);if(!data?.length)return;h.innerHTML=data.map(o=>{const c=o.currency_code||o.source_currency||'';let m='';if(c&&(o.min_amount!=null||o.max_amount!=null)){const f=n=>new Intl.NumberFormat(`${s.language}-${s.country||'US'}`,{style:'currency',currency:c}).format(Number(n));m=`${o.min_amount!=null?f(o.min_amount):''}${o.max_amount!=null?' – '+f(o.max_amount):''}`;}return `<article class="opportunity"><div><span class="tag">${esc(o.category||'OPPORTUNITY')}</span><h4>${esc(o.title)}</h4><p>${esc(o.country_code||o.region||'Global')} · ${esc(m||'Source currency shown')}</p></div><b>${esc(o.score||'—')}</b></article>`}).join('');}
document.addEventListener('DOMContentLoaded',()=>{inject();globalCopy();refreshOpp();});setTimeout(inject,600);
})();