(() => {
  const esc = s => String(s ?? '').replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const toast = msg => { const el=document.createElement('div'); el.className='or5-toast'; el.textContent=msg; document.body.appendChild(el); setTimeout(()=>el.remove(),3200); };
  const css = document.createElement('style'); css.textContent=`
    .or5-shell{max-width:1180px;margin:30px auto 90px;padding:0 20px;display:grid;gap:18px}
    .or5-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:14px}.or5-card{background:linear-gradient(145deg,rgba(16,35,58,.94),rgba(8,20,35,.96));border:1px solid #203b58;border-radius:20px;padding:20px;box-shadow:0 18px 50px rgba(0,0,0,.18)}
    .or5-card h3{margin:0 0 8px;font:700 20px 'Space Grotesk',sans-serif}.or5-card p{color:#9fb0c7;line-height:1.55}.or5-wide{grid-column:1/-1}.or5-actions{display:flex;flex-wrap:wrap;gap:9px;margin-top:14px}.or5-btn{border:1px solid #2b4d70;background:#102844;color:#f5f8ff;border-radius:12px;padding:10px 13px;cursor:pointer}.or5-btn.primary{background:linear-gradient(135deg,#2563eb,#7c5cff);border:0}.or5-input,.or5-select{width:100%;margin-top:7px;padding:11px 12px;border-radius:11px;border:1px solid #294764;background:#081728;color:#f5f8ff}.or5-label{display:block;color:#c9d5e5;font-size:13px;margin-top:10px}.or5-tags{display:flex;flex-wrap:wrap;gap:7px;margin-top:10px}.or5-tag{padding:6px 9px;border-radius:999px;background:#122b46;color:#bdefff;font-size:12px}.or5-item{padding:13px 0;border-bottom:1px solid #20344e}.or5-item:last-child{border-bottom:0}.or5-score{font-weight:700;color:#42df91}.or5-kpi{font:700 28px 'Space Grotesk';color:#f5f8ff}.or5-muted{color:#9fb0c7;font-size:13px}.or5-toast{position:fixed;right:18px;bottom:18px;z-index:99999;background:#102844;color:#fff;border:1px solid #2b4d70;padding:13px 16px;border-radius:12px;box-shadow:0 15px 40px #0008}.or5-hidden{display:none!important}@media(max-width:850px){.or5-grid{grid-template-columns:1fr}.or5-wide{grid-column:auto}}
  `; document.head.appendChild(css);
  const shell=document.createElement('section'); shell.id='or5Shell'; shell.className='or5-shell'; shell.innerHTML=`
    <div class="or5-card or5-wide"><div class="or5-muted">OPPORTUNITY RADAR · PHASES 1–5</div><h2 style="font-family:'Space Grotesk';font-size:30px;margin:5px 0">Your personal opportunity command center</h2><p>Discover opportunities, prove skills, build trust, and track your next move from one place.</p><div class="or5-actions"><button class="or5-btn primary" id="or5Personalize">Personalize my Radar</button><button class="or5-btn" id="or5Refresh">Refresh matches</button></div></div>
    <div class="or5-grid"><div class="or5-card"><div class="or5-muted">MATCHES</div><div class="or5-kpi" id="or5MatchCount">—</div><p>Opportunities currently aligned with your profile.</p></div><div class="or5-card"><div class="or5-muted">SKILL PASSPORT</div><div class="or5-kpi" id="or5SkillCount">—</div><p>Skills and evidence collected so far.</p></div><div class="or5-card"><div class="or5-muted">TRUST</div><div class="or5-kpi" id="or5Trust">Building</div><p>Your evidence becomes more useful as it is verified.</p></div></div>
    <div class="or5-card or5-wide"><h3>🎯 My Radar</h3><div id="or5Matches"><p>Loading personalized matches…</p></div></div>
    <div class="or5-card or5-wide"><h3>🪪 Skill Passport</h3><div class="or5-grid"><div><label class="or5-label">Skill</label><input class="or5-input" id="or5Skill" placeholder="e.g. Python"><label class="or5-label">Level</label><select class="or5-select" id="or5Level"><option>beginner</option><option>intermediate</option><option>advanced</option></select><div class="or5-actions"><button class="or5-btn primary" id="or5AddSkill">Add skill</button></div></div><div class="or5-wide" style="grid-column:span 2"><div id="or5Skills"><p>No skills added yet.</p></div></div></div></div>
    <div class="or5-card or5-wide"><h3>🏢 Organization Studio</h3><p>Organizations can create a verified profile and submit opportunities for review. Nothing becomes public until it passes moderation.</p><div class="or5-grid"><div><label class="or5-label">Organization name</label><input class="or5-input" id="or5OrgName" placeholder="Organization name"><label class="or5-label">Website</label><input class="or5-input" id="or5OrgWeb" placeholder="https://example.org"><button class="or5-btn primary" id="or5CreateOrg" style="margin-top:12px">Create organization profile</button></div><div class="or5-wide" style="grid-column:span 2"><div id="or5OrgStatus"><p>No organization profile yet.</p></div></div></div></div>
    <div class="or5-card or5-wide or5-hidden" id="or5OpportunityForm"><h3>Submit an opportunity</h3><div class="or5-grid"><div><label class="or5-label">Title</label><input class="or5-input" id="or5OppTitle"><label class="or5-label">Category</label><select class="or5-select" id="or5OppCat"><option>Scholarship</option><option>Competition</option><option>Program</option><option>Learning</option><option>Internship</option></select></div><div><label class="or5-label">Destination URL</label><input class="or5-input" id="or5OppUrl"><label class="or5-label">Deadline</label><input class="or5-input" id="or5OppDeadline" type="datetime-local"></div><div><label class="or5-label">Description</label><textarea class="or5-input" id="or5OppDesc" rows="5"></textarea><button class="or5-btn primary" id="or5SubmitOpp" style="margin-top:12px">Submit for review</button></div></div></div>
  `; document.body.insertBefore(shell,document.body.lastElementChild);

  const getUser=()=>window.verifiedUser || null;
  async function profile(){const u=getUser();if(!u)return null; const [{data:p},{data:pref}]=await Promise.all([db.from('profiles').select('*').eq('id',u.id).maybeSingle(),db.from('radar_user_preferences').select('*').eq('user_id',u.id).maybeSingle()]);return {...(p||{}),...(pref||{})};}
  async function loadMatches(){const u=getUser();if(!u)return; const p=await profile(); let q=db.from('opportunities').select('id,title,category,region,skills,description,source_name,source_url,deadline,score,verified,verification_status,minimum_age').eq('verification_status','verified').order('score',{ascending:false}).limit(60); const {data:ops,error}=await q; if(error){$('or5Matches').innerHTML='<p>Matches are temporarily unavailable.</p>';return;} const interests=(p?.interests||[]).map(x=>x.toLowerCase()), skills=(p?.skills||[]).map(x=>x.toLowerCase()), goals=(p?.career_goals||[]).map(x=>x.toLowerCase()), country=String(p?.country_code||'').toLowerCase(); const ranked=(ops||[]).map(o=>{const text=((o.title||'')+' '+(o.description||'')+' '+(o.category||'')+' '+(o.region||'')+' '+(o.skills||[]).join(' ')).toLowerCase(); let s=Number(o.score||50); interests.forEach(x=>{if(text.includes(x))s+=9});skills.forEach(x=>{if(text.includes(x))s+=10});goals.forEach(x=>{if(text.includes(x))s+=6});if(country&&text.includes(country))s+=8;if(/global|remote|worldwide/.test(text))s+=5;return {...o,match:Math.min(99,s)}}).sort((a,b)=>b.match-a.match).slice(0,8)); $('or5MatchCount').textContent=ranked.length; $('or5Matches').innerHTML=ranked.length?ranked.map(o=>`<div class="or5-item"><div><span class="or5-score">${o.match}% match</span> · ${esc(o.category||'Opportunity')}</div><strong>${esc(o.title)}</strong><div class="or5-muted">${esc(o.region||'Global')} · ${esc(o.source_name||'Verified source')}</div><div class="or5-actions"><button class="or5-btn" data-open-opp="${esc(o.source_url||'#')}">View opportunity</button></div></div>`).join(''):'<p>Complete your profile to unlock stronger matches.</p>'; document.querySelectorAll('[data-open-opp]').forEach(b=>b.onclick=()=>window.open(b.dataset.openOpp,'_blank','noopener'));}
  async function loadSkills(){const u=getUser();if(!u)return;const {data}=await db.from('radar_skill_items').select('*').eq('user_id',u.id).order('updated_at',{ascending:false});$('or5SkillCount').textContent=(data||[]).length; $('or5Skills').innerHTML=(data||[]).length?(data||[]).map(s=>`<div class="or5-item"><strong>${esc(s.skill_name)}</strong> <span class="or5-tag">${esc(s.level)}</span> ${s.verified?'<span class="or5-tag">✓ verified</span>':''}</div>`).join(''):'<p>No skills added yet. Start your passport with one real skill.</p>';}
  async function loadOrg(){const u=getUser();if(!u)return;const {data:o}=await db.from('radar_organizations').select('*').eq('owner_user_id',u.id).maybeSingle();if(o){$('or5OrgName').value=o.name||'';$('or5OrgWeb').value=o.website||'';$('or5OrgStatus').innerHTML=`<p><strong>${esc(o.name)}</strong><br>Status: <span class="or5-tag">${esc(o.verification_status)}</span> · Trust score ${Number(o.trust_score||0)}</p>`;$('or5OpportunityForm').classList.remove('or5-hidden');$('or5OpportunityForm').dataset.org=o.id;} }
  $('or5Personalize').onclick=async()=>{const p=await profile();const country=prompt('Country code (e.g. NG, US, GB)',p?.country_code||'')||p?.country_code||'';const education=prompt('Education level',p?.education_level||'')||p?.education_level||'';const interests=(prompt('Interests, comma separated',((p?.interests)||[]).join(', '))||'').split(',').map(x=>x.trim()).filter(Boolean);const skills=(prompt('Skills, comma separated',((p?.skills)||[]).join(', '))||'').split(',').map(x=>x.trim()).filter(Boolean);const goals=(prompt('Career goals, comma separated',((p?.career_goals)||[]).join(', '))||'').split(',').map(x=>x.trim()).filter(Boolean);const u=getUser();if(!u)return;await db.from('radar_user_preferences').upsert({user_id:u.id,country_code:country.toUpperCase(),education_level:education,interests,skills,career_goals:goals,updated_at:new Date().toISOString()},{onConflict:'user_id'});await db.from('profiles').upsert({id:u.id,country_code:country.toUpperCase(),education_level:education,interests,skills,career_goals:goals},{onConflict:'id'});toast('Radar profile updated');loadMatches();};
  $('or5Refresh').onclick=loadMatches;
  $('or5AddSkill').onclick=async()=>{const u=getUser(),name=$('or5Skill').value.trim(),level=$('or5Level').value;if(!u||!name)return;const {error}=await db.from('radar_skill_items').upsert({user_id:u.id,skill_name:name,level,updated_at:new Date().toISOString()},{onConflict:'user_id,skill_name'});if(error)toast(error.message);else{toast('Skill added to your Passport');$('or5Skill').value='';loadSkills();loadMatches();}};
  $('or5CreateOrg').onclick=async()=>{const u=getUser(),name=$('or5OrgName').value.trim(),website=$('or5OrgWeb').value.trim();if(!u||!name)return toast('Add an organization name first');const {data,error}=await db.from('radar_organizations').upsert({owner_user_id:u.id,name,website,verification_status:'pending'},{onConflict:'owner_user_id'}).select().single();if(error)toast(error.message);else{toast('Organization profile created and queued for verification');loadOrg();}};
  $('or5SubmitOpp').onclick=async()=>{const org=$('or5OpportunityForm').dataset.org,u=getUser();if(!org||!u)return;const payload={organization_id:org,title:$('or5OppTitle').value.trim(),category:$('or5OppCat').value,description:$('or5OppDesc').value.trim(),destination_url:$('or5OppUrl').value.trim(),deadline:$('or5OppDeadline').value?new Date($('or5OppDeadline').value).toISOString():null};if(!payload.title||!payload.description||!payload.destination_url)return toast('Complete the opportunity fields');const {error}=await db.from('radar_org_opportunities').insert(payload);if(error)toast(error.message);else{toast('Opportunity submitted for review');['or5OppTitle','or5OppDesc','or5OppUrl','or5OppDeadline'].forEach(id=>$(id).value='');}};
  const boot=async()=>{if(!getUser()){setTimeout(boot,800);return;} shell.classList.remove('or5-hidden'); await Promise.all([loadMatches(),loadSkills(),loadOrg()]);}; boot();
})();
