(()=>{
 const db=window.db;
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const toast=m=>{const t=document.createElement('div');t.textContent=m;t.style.cssText='position:fixed;right:18px;bottom:18px;z-index:9999;background:#10233a;border:1px solid #294766;color:#fff;padding:12px 15px;border-radius:12px;box-shadow:0 12px 40px #0008';document.body.appendChild(t);setTimeout(()=>t.remove(),3200)};
 const section=document.getElementById('project-vault'); if(!section||!db)return;
 section.innerHTML=`<div class="section-head"><div><span class="eyebrow">RADAR PRO · PROJECT VAULT</span><h2>Find real projects. Understand them. Build your own.</h2><p>Search public GitHub projects by what you want to create. Radar explains the project, shows the stack, and turns it into a learning path.</p></div><span class="tag">PRO</span></div><div class="pv-shell"><div class="pv-search"><input id="pvQuery" placeholder="Try: real estate website, WhatsApp bot, Discord bot, AI app..."/><button class="btn primary" id="pvSearch">Search Project Vault →</button></div><div class="pv-presets"><button class="chip" data-q="real estate website">Real estate</button><button class="chip" data-q="WhatsApp bot">WhatsApp bot</button><button class="chip" data-q="Discord bot">Discord bot</button><button class="chip" data-q="AI application">AI app</button><button class="chip" data-q="ecommerce website">E-commerce</button><button class="chip" data-q="developer portfolio">Portfolio</button></div><div id="pvStatus" class="pv-status"></div><div id="pvResults" class="pv-results"></div></div>`;
 const style=document.createElement('style');style.textContent=`#project-vault{scroll-margin-top:90px}.pv-shell{background:linear-gradient(145deg,rgba(12,26,43,.96),rgba(9,20,35,.92));border:1px solid #20344e;border-radius:22px;padding:20px;box-shadow:0 24px 70px #0004}.pv-search{display:grid;grid-template-columns:1fr auto;gap:10px}.pv-search input{width:100%;background:#081522;border:1px solid #28415d;color:#fff;border-radius:13px;padding:14px 15px;outline:none}.pv-search input:focus{border-color:#43d9ff;box-shadow:0 0 0 3px #43d9ff14}.pv-presets{display:flex;gap:8px;flex-wrap:wrap;margin:12px 0}.pv-status{color:#9fb0c7;min-height:24px;padding:5px 0}.pv-results{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.pv-card{background:#0a1727;border:1px solid #20344e;border-radius:18px;padding:17px;transition:.2s transform,.2s border-color}.pv-card:hover{transform:translateY(-2px);border-color:#356486}.pv-meta{display:flex;gap:7px;flex-wrap:wrap;margin:8px 0}.pv-meta span{font-size:11px;color:#b8c9dc;border:1px solid #28415d;background:#0e2034;border-radius:999px;padding:5px 8px}.pv-card h3{margin:0 0 6px;font-size:18px}.pv-card p{color:#9fb0c7;line-height:1.55;font-size:13px}.pv-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px}.pv-actions button,.pv-actions a{font-size:12px;text-decoration:none}.pv-detail{display:none;margin-top:12px;padding-top:12px;border-top:1px solid #20344e}.pv-detail.on{display:block}.pv-detail ol{padding-left:20px;color:#b8c9dc;line-height:1.7}.pv-detail strong{color:#fff}.pv-saved{color:#42df91}.pv-pro{padding:26px;text-align:center;border:1px dashed #31516f;border-radius:16px;background:#0a1727}.pv-pro h3{margin:0 0 8px}.pv-empty{text-align:center;color:#8fa4ba;padding:35px}.chip.on{background:#153e57;color:#fff}@media(max-width:760px){.pv-search{grid-template-columns:1fr}.pv-results{grid-template-columns:1fr}}`;document.head.appendChild(style);
 const qInput=document.getElementById('pvQuery'), results=document.getElementById('pvResults'), status=document.getElementById('pvStatus');
 let user=null, saved=new Set();
 function card(p){const id=p.github_id;return `<article class="pv-card"><div style="display:flex;justify-content:space-between;gap:10px"><div><span class="tag">${esc(p.category||'Project')}</span><h3>${esc(p.name)}</h3></div><span class="pv-meta"><span>★ ${Number(p.stars||0).toLocaleString()}</span></span></div><p>${esc(p.description||'No description provided.')}</p><div class="pv-meta"><span>${esc(p.language||'Multi-stack')}</span><span>${esc(p.difficulty||'Reference')}</span><span>${esc(p.license_spdx||'License check')}</span><span>${p.forks||0} forks</span></div><p><strong>Why it matches:</strong> ${esc(p.explanation||'Useful as a reference project.')}</p><div class="pv-actions"><a class="btn" href="${esc(p.html_url)}" target="_blank" rel="noopener noreferrer">Original GitHub ↗</a>${p.homepage?`<a class="btn" href="${esc(p.homepage)}" target="_blank" rel="noopener noreferrer">Live demo ↗</a>`:''}<button class="btn" data-explain="${esc(String(id))}">Build path</button><button class="btn" data-save="${esc(String(id))}">${saved.has(String(id))?'✓ Saved':'Save'}</button></div><div class="pv-detail" id="pv-detail-${esc(String(id))}"><strong>Build path</strong><ol>${(p.build_path||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ol><strong>Trust note</strong><p>${esc(p.security_note||'Review dependencies and configuration before running third-party code.')}</p></div></article>`}
 async function loadSaved(){if(!user)return;const {data}=await db.from('project_vault_saves').select('project_id,project_vault_projects(github_id)').eq('user_id',user.id);saved=new Set((data||[]).map(x=>String(x.project_vault_projects?.github_id)).filter(Boolean));}
 async function save(gid){const {data:proj}=await db.from('project_vault_projects').select('id').eq('github_id',Number(gid)).maybeSingle();if(!proj)return toast('Project is not cached yet');if(saved.has(String(gid))){const {error}=await db.from('project_vault_saves').delete().eq('user_id',user.id).eq('project_id',proj.id);if(error)toast(error.message);else{saved.delete(String(gid));toast('Removed from your Vault');}}else{const {error}=await db.from('project_vault_saves').insert({user_id:user.id,project_id:proj.id});if(error)toast(error.message);else{saved.add(String(gid));toast('Saved to your Project Vault');}}document.querySelectorAll('[data-save="'+gid+'"]').forEach(b=>b.textContent=saved.has(String(gid))?'✓ Saved':'Save');}
 async function search(){const query=qInput.value.trim();if(!query)return;status.textContent='Searching GitHub and building your project map…';results.innerHTML='';const {data,error}=await db.functions.invoke('project-vault-search',{body:{query}});if(error){status.textContent='';try{const j=JSON.parse(error.context?.body||'{}');if(j.code==='PRO_REQUIRED')results.innerHTML='<div class="pv-pro"><h3>Project Vault is a Radar Pro feature</h3><p>Upgrade to unlock project discovery, explanations, build paths and saved projects.</p><a class="btn primary" href="#radar-pro">View Radar Pro</a></div>';else results.innerHTML='<div class="pv-empty">'+esc(j.error||error.message)+'</div>';}catch(_){results.innerHTML='<div class="pv-empty">'+esc(error.message)+'</div>';}return}status.textContent=data?.projects?.length?`${data.projects.length} projects found · search expanded to ${data.expanded_terms?.length||0} related terms`:'No strong matches found. Try a broader project description.';results.innerHTML=(data?.projects||[]).map(card).join('')||'<div class="pv-empty">No projects found.</div>';document.querySelectorAll('[data-explain]').forEach(b=>b.onclick=()=>document.getElementById('pv-detail-'+b.dataset.explain)?.classList.toggle('on'));document.querySelectorAll('[data-save]').forEach(b=>b.onclick=()=>save(b.dataset.save));}
 document.getElementById('pvSearch').onclick=search;qInput.addEventListener('keydown',e=>{if(e.key==='Enter')search()});document.querySelectorAll('[data-q]').forEach(b=>b.onclick=()=>{qInput.value=b.dataset.q;search()});
 async function boot(){const {data}=await db.auth.getUser();user=(data?.user?.email_confirmed_at)?data.user:null;if(!user){section.style.display='none';setTimeout(boot,1200);return}section.style.display='block';await loadSaved();}
 document.querySelectorAll('[data-scroll="project-vault"]').forEach(b=>b.onclick=()=>{section.style.display='block';section.scrollIntoView({behavior:'smooth'})});boot();
})();