-- Global-first localization and flexible competition stages
CREATE TABLE IF NOT EXISTS public.countries (country_code text PRIMARY KEY, country_code3 text, numeric_code text, name text NOT NULL, region text, active boolean NOT NULL DEFAULT true);
CREATE TABLE IF NOT EXISTS public.currencies (currency_code text PRIMARY KEY, numeric_code text, name text NOT NULL, minor_units smallint, active boolean NOT NULL DEFAULT true);
CREATE TABLE IF NOT EXISTS public.languages (language_code text PRIMARY KEY, name text NOT NULL, active boolean NOT NULL DEFAULT true);
CREATE TABLE IF NOT EXISTS public.country_locales (country_code text PRIMARY KEY REFERENCES public.countries(country_code) ON DELETE CASCADE, default_currency text REFERENCES public.currencies(currency_code), default_language text REFERENCES public.languages(language_code), default_locale text NOT NULL DEFAULT 'en', default_timezone text NOT NULL DEFAULT 'UTC', supported_languages text[] NOT NULL DEFAULT '{}');
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS country_code text REFERENCES public.countries(country_code), ADD COLUMN IF NOT EXISTS preferred_currency text REFERENCES public.currencies(currency_code), ADD COLUMN IF NOT EXISTS preferred_language text REFERENCES public.languages(language_code), ADD COLUMN IF NOT EXISTS locale text, ADD COLUMN IF NOT EXISTS timezone text;
ALTER TABLE public.opportunities ADD COLUMN IF NOT EXISTS country_code text REFERENCES public.countries(country_code), ADD COLUMN IF NOT EXISTS currency_code text REFERENCES public.currencies(currency_code), ADD COLUMN IF NOT EXISTS min_amount numeric, ADD COLUMN IF NOT EXISTS max_amount numeric, ADD COLUMN IF NOT EXISTS display_currency text REFERENCES public.currencies(currency_code), ADD COLUMN IF NOT EXISTS source_currency text REFERENCES public.currencies(currency_code), ADD COLUMN IF NOT EXISTS exchange_rate numeric, ADD COLUMN IF NOT EXISTS exchange_rate_updated_at timestamptz, ADD COLUMN IF NOT EXISTS settlement_currency text REFERENCES public.currencies(currency_code);
ALTER TABLE public.competitions ADD COLUMN IF NOT EXISTS stage_model text NOT NULL DEFAULT 'custom', ADD COLUMN IF NOT EXISTS stage_scope text NOT NULL DEFAULT 'global';
CREATE TABLE IF NOT EXISTS public.competition_stages (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), competition_id uuid NOT NULL REFERENCES public.competitions(id) ON DELETE CASCADE, stage_key text NOT NULL, stage_name text NOT NULL, scope_type text NOT NULL, scope_code text, sequence_no integer NOT NULL, advancement_rule jsonb NOT NULL DEFAULT '{}'::jsonb, eligibility_rule jsonb NOT NULL DEFAULT '{}'::jsonb, starts_at timestamptz, ends_at timestamptz, active boolean NOT NULL DEFAULT true, UNIQUE(competition_id, stage_key));
CREATE INDEX IF NOT EXISTS idx_opportunities_country_code ON public.opportunities(country_code);
CREATE INDEX IF NOT EXISTS idx_competition_stages_competition ON public.competition_stages(competition_id, sequence_no);
CREATE OR REPLACE VIEW public.global_country_directory AS SELECT c.country_code,c.country_code3,c.name,c.region,cl.default_currency,cl.default_language,cl.default_locale,cl.default_timezone,cl.supported_languages FROM public.countries c LEFT JOIN public.country_locales cl ON cl.country_code=c.country_code WHERE c.active=true;